# These are supported funding model platforms

ko_fi: sinduy # Replace with a single Ko-fi username
patreon: dfgHiatus # Replace with a single Patreon username
ko_fi: dfghiatus # Replace with a single Ko-fi username
